/// Flutter icons NicamalIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NicamalIcons
///      fonts:
///       - asset: fonts/NicamalIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NicamalIcons {
  NicamalIcons._();

  static const _kFontFam = 'NicamalIcons';
  static const String _kFontPkg = null;

  static const IconData adop =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grupo_124 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
